[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "chat_server"
path = "src/biDirectionalChat/server.rs"

[[bin]]
name = "chat_client"
path = "src/biDirectionalChat/client.rs"
